# Generated by Django 4.2.16 on 2024-10-10 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news_microservice_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newsarticle",
            old_name="image",
            new_name="image_url",
        ),
    ]
