# Generated by Django 4.2.16 on 2024-10-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_home', models.CharField(max_length=500)),
                ('team_away', models.CharField(max_length=500)),
                ('score_home', models.IntegerField()),
                ('score_away', models.IntegerField()),
                ('location', models.CharField(max_length=500)),
                ('division', models.CharField(max_length=500)),
                ('video_url', models.URLField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo_url', models.URLField(max_length=1000)),
            ],
        ),
    ]
