# Generated by Django 4.2.16 on 2024-10-09 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match_microservice_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutFcKokoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played', models.IntegerField(default=0, verbose_name='Количество игр')),
                ('wins', models.IntegerField(default=0, verbose_name='Победы')),
                ('goals_scored', models.IntegerField(default=0, verbose_name='Голы')),
                ('tournaments', models.IntegerField(default=0, verbose_name='Турниры')),
                ('about_text', models.TextField(blank=True, null=True, verbose_name='Информация о команде')),
            ],
            options={
                'verbose_name': 'О клубе',
                'verbose_name_plural': 'О клубе',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='match_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата матча'),
        ),
        migrations.AddField(
            model_name='match',
            name='match_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время матча'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_away',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='match_microservice_app.team'),
        ),
    ]
