# Generated by Django 4.2.16 on 2024-10-10 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match_microservice_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutFcKokoc',
        ),
    ]
