# Generated by Django 4.2.16 on 2024-10-10 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match_microservice_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='match',
            table='match',
        ),
    ]
