# Generated by Django 5.1.2 on 2024-10-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_microservice_app', '0002_aboutfckokoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='about_text',
            field=models.TextField(blank=True, null=True, verbose_name='Информация о команде'),
        ),
        migrations.AddField(
            model_name='match',
            name='match_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время матча'),
        ),
    ]
