# Generated by Django 5.1.2 on 2024-10-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_microservice_app', '0003_match_about_text_match_match_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='match_date_time',
        ),
        migrations.AddField(
            model_name='match',
            name='match_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата матча'),
        ),
        migrations.AddField(
            model_name='match',
            name='match_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время матча'),
        ),
    ]
