# Generated by Django 5.1.2 on 2024-10-09 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_microservice_app', '0005_remove_match_about_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team_away',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='match_microservice_app.team'),
        ),
    ]
