# Generated by Django 4.2.16 on 2024-10-10 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kokoc_team_microservice_app', '0002_aboutfckokoc'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aboutfckokoc',
            table='about_fc_kokoc',
        ),
    ]
