# Generated by Django 4.2.16 on 2024-10-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_microservice_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Обработан', 'Обработан'), ('В ожидании', 'В ожидании')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Одежда', 'Одежда'), ('Аксессуары', 'Аксессуары')], max_length=255),
        ),
    ]
