# Generated by Django 4.2.16 on 2024-10-12 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_microservice_app', '0002_alter_order_status_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='Order',
        ),
    ]
