# Generated by Django 4.2.16 on 2024-10-12 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_microservice_app', '0003_alter_order_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='product_id',
        ),
    ]
