# Generated by Django 4.2.16 on 2024-10-12 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_microservice_app', '0004_rename_product_cartitem_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_id',
            new_name='product',
        ),
    ]
