# Generated by Django 4.2.16 on 2024-10-04 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_microservice', '0002_refreshtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
